use MY_DB;

insert into signup_invitation values (1, 'keerthu@gmail.com', 'NEWOFFER');

insert into user values (1, 'vicky', 'vickyavw.10@gmail.com', 'smRGLv5svAXvMiz6m+PFhfqGY4BU+RmziklDk4O7uU8zXUt+9euFVsH0Tv1NxYhO');

insert into api values (1, 'getCountriesList', 10, 0);
insert into api values (2, 'getCountryByCode', 5, 0);

insert into user_api_quota values (1, 1, 10);
insert into user_api_quota values (1, 2, 10);

-- Countries of the world
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Albania','AL','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Afghanistan','AF','Y',1946);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Algeria','DZ','Y',1962);
insert into country (country_name, country_code, UN_member) values ('American Samoa','AS','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Andorra','AD','Y',1993);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Angola','AO','Y',1976);
insert into country (country_name, country_code, UN_member) values ('Anguilla','AI','N');
insert into country (country_name, country_code, UN_member) values ('Antarctica','AQ','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Antigua And Barbuda','AG','Y',1981);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Argentina','AR','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Armenia','AM','Y',1992);
insert into country (country_name, country_code, UN_member) values ('Aruba','AW','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Australia','AU','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Austria','AT','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Azerbaijan','AZ','Y',1992);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Bahamas','BS','Y',1973);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Bahrain','BH','Y',1971);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Bangladesh','BD','Y',1974);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Barbados','BB','Y',1966);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Belarus','BY','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Belgium','BE','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Belize','BZ','Y',1981);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Benin','BJ','Y',1960);
insert into country (country_name, country_code, UN_member) values ('Bermuda','BM','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Bhutan','BT','Y',1971);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Bolivia','BO','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Bosnia And Herzegovina','BA','Y',1992);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Botswana','BW','Y',1966);
insert into country (country_name, country_code, UN_member) values ('Bouvet Island','BV','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Brazil','BR','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Brunei','BN','Y',1984);
insert into country (country_name, country_code, UN_member) values ('British Indian Ocean Territory','IO','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Bulgaria','BG','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Burkina Faso','BF','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Burundi','BI','Y',1962);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Cambodia','KH','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Cameroon','CM','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Canada','CA','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Cape Verde','CV','Y',1975);
insert into country (country_name, country_code, UN_member) values ('Cayman Islands','KY','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Central African Republic','CF','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Chad','TD','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Chile','CL','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('China','CN','Y',1945);
insert into country (country_name, country_code, UN_member) values ('Christmas Island','CX','N');
insert into country (country_name, country_code, UN_member) values ('Cocos (keeling) Islands','CC','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Colombia','CO','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Comoros','KM','Y',1975);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Congo, Rep. of','CG','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Congo, Dem. Rep. of','CD','Y',1960);
insert into country (country_name, country_code, UN_member) values ('Cook Islands','CK','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Costa Rica','CR','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Cote Divoire','CI','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Croatia','HR','Y',1992);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Cuba','CU','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Cyprus','CY','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Czech Republic','CZ','Y',1993);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Denmark','DK','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Djibouti','DJ','Y',1977);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Dominica','DM','Y',1978);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Dominican Republic','DO','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('East Timor','TP','Y',2002);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Ecuador','EC','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Egypt','EG','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('El Salvador','SV','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Equatorial Guinea','GQ','Y',1968);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Eritrea','ER','Y',1993);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Estonia','EE','Y',1991);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Ethiopia','ET','Y',1945);
insert into country (country_name, country_code, UN_member) values ('Falkland Islands (malvinas)','FK','N');
insert into country (country_name, country_code, UN_member) values ('Faroe Islands','FO','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Fiji','FJ','Y',1970);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Finland','FI','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('France','FR','Y',1945);
insert into country (country_name, country_code, UN_member) values ('French Guiana','GF','N');
insert into country (country_name, country_code, UN_member) values ('French Polynesia','PF','N');
insert into country (country_name, country_code, UN_member) values ('French Southern Territories','TF','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Gabon','GA','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Gambia','GM','Y',1965);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Georgia','GE','Y',1992);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Germany','DE','Y',1973);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Ghana','GH','Y',1957);
insert into country (country_name, country_code, UN_member) values ('Gibraltar','GI','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Greece','GR','Y',1945);
insert into country (country_name, country_code, UN_member) values ('Greenland','GL','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Grenada','GD','Y',1974);
insert into country (country_name, country_code, UN_member) values ('Guadeloupe','GP','N');
insert into country (country_name, country_code, UN_member) values ('Guam','GU','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Guatemala','GT','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Guinea','GN','Y',1958);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Guinea-bissau','GW','Y',1974);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Guyana','GY','Y',1966);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Haiti','HT','Y',1945);
insert into country (country_name, country_code, UN_member) values ('Heard Island And Mcdonald Islands','HM','N');
insert into country (country_name, country_code, UN_member) values ('Holy See (vatican City State)','VA','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Honduras','HN','Y',1945);
insert into country (country_name, country_code, UN_member) values ('Hong Kong','HK','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Hungary','HU','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Iceland','IS','Y',1946);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('India','IN','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Indonesia','ID','Y',1950);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Iran','IR','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Iraq','IQ','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Ireland','IE','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Israel','IL','Y',1949);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Italy','IT','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Jamaica','JM','Y',1962);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Japan','JP','Y',1956);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Jordan','JO','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Kazakstan','KZ','Y',1992);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Kenya','KE','Y',1963);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Kiribati','KI','Y',1999);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Korea, Nrth','KP','Y',1991);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Korea, South','KR','Y',1991);
insert into country (country_name, country_code, UN_member) values ('Kosovo','KV','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Kuwait','KW','Y',1963);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Kyrgyzstan','KG','Y',1992);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Laos','LA','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Latvia','LV','Y',1991);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('LebaNn','LB','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Lesotho','LS','Y',1966);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Liberia','LR','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Libya','LY','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Liechtenstein','LI','Y',1990);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Lithuania','LT','Y',1991);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Luxembourg','LU','Y',1945);
insert into country (country_name, country_code, UN_member) values ('Macau','MO','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Macedonia','MK','Y',1993);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Madagascar','MG','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Malawi','MW','Y',1964);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Malaysia','MY','Y',1957);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Maldives','MV','Y',1965);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Mali','ML','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Malta','MT','Y',1964);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Marshall Islands','MH','Y',1991);
insert into country (country_name, country_code, UN_member) values ('Martinique','MQ','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Mauritania','MR','Y',1961);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Mauritius','MU','Y',1968);
insert into country (country_name, country_code, UN_member) values ('Mayotte','YT','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Mexico','MX','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Micronesia','FM','Y',1991);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Moldova','MD','Y',1992);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Monaco','MC','Y',1993);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Mongolia','MN','Y',1961);
insert into country (country_name, country_code, UN_member) values ('Montserrat','MS','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Montenegro','ME','Y',2006);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Morocco','MA','Y',1956);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Mozambique','MZ','Y',1975);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Myanmar','MM','Y',1948);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Namibia','NA','Y',1990);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Nauru','NR','Y',1999);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Nepal','NP','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Netherlands','NL','Y',1945);
insert into country (country_name, country_code, UN_member) values ('Netherlands Antilles','AN','N');
insert into country (country_name, country_code, UN_member) values ('New Caledonia','NC','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('New Zealand','NZ','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Nicaragua','NI','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Niger','NE','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Nigeria','NG','Y',1960);
insert into country (country_name, country_code, UN_member) values ('Niue','NU','N');
insert into country (country_name, country_code, UN_member) values ('Nrfolk Island','NF','N');
insert into country (country_name, country_code, UN_member) values ('Nrthern Mariana Islands','MP','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Nrway','N','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Oman','OM','Y',1971);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Pakistan','PK','Y',1947);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Palau','PW','Y',1994);
insert into country (country_name, country_code, UN_member) values ('Palestinian Territory, Occupied','PS','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Panama','PA','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Papua New Guinea','PG','Y',1975);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Paraguay','PY','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Peru','PE','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Philippines','PH','Y',1945);
insert into country (country_name, country_code, UN_member) values ('Pitcairn','PN','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Poland','PL','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Portugal','PT','Y',1955);
insert into country (country_name, country_code, UN_member) values ('Puerto Rico','PR','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Qatar','QA','Y',1971);
insert into country (country_name, country_code, UN_member) values ('Reunion','RE','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Romania','RO','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Russia','RU','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Rwanda','RW','Y',1962);
insert into country (country_name, country_code, UN_member) values ('Saint Helena','SH','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Saint Kitts And Nevis','KN','Y',1983);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Saint Lucia','LC','Y',1979);
insert into country (country_name, country_code, UN_member) values ('Saint Pierre And Miquelon','PM','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Saint Vincent And The Grenadines','VC','Y',1980);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Samoa','WS','Y',1976);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('San MariN','SM','Y',1992);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Sao Tome And Principe','ST','Y',1975);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Saudi Arabia','SA','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Senegal','SN','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Serbia','RS','Y',2000);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Seychelles','SC','Y',1976);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Sierra Leone','SL','Y',1961);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Singapore','SG','Y',1965);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Slovakia','SK','Y',1993);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Slovenia','SI','Y',1992);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Solomon Islands','SB','Y',1978);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Somalia','SO','Y',1960);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('South Africa','ZA','Y',1945);
insert into country (country_name, country_code, UN_member) values ('South Georgia Islands','GS','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Spain','ES','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Sri Lanka','LK','Y',1955);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Sudan','SD','Y',1956);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Suriname','SR','Y',1975);
insert into country (country_name, country_code, UN_member) values ('Svalbard And Jan Mayen','SJ','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Swaziland','SZ','Y',1968);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Sweden','SE','Y',1946);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Switzerland','CH','Y',2002);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Syria','SY','Y',1945);
insert into country (country_name, country_code, UN_member) values ('Taiwan, Province Of China','TW','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Tajikistan','TJ','Y',1992);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Tanzania','TZ','Y',1961);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Thailand','TH','Y',1946);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Togo','TG','Y',1960);
insert into country (country_name, country_code, UN_member) values ('Tokelau','TK','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Tonga','TO','Y',1999);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Trinidad And Tobago','TT','Y',1962);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Tunisia','TN','Y',1956);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Turkey','TR','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Turkmenistan','TM','Y',1992);
insert into country (country_name, country_code, UN_member) values ('Turks And Caicos Islands','TC','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Tuvalu','TV','Y',2000);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Uganda','UG','Y',1962);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Ukraine','UA','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('United Arab Emirates','AE','Y',1971);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('United Kingdom','GB','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('United States','US','Y',1945);
insert into country (country_name, country_code, UN_member) values ('United States MiNr Outlying Islands','UM','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Uruguay','UY','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Uzbekistan','UZ','Y',1992);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Vanuatu','VU','Y',1981);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Venezuela','VE','Y',1945);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Vietnam','VN','Y',1977);
insert into country (country_name, country_code, UN_member) values ('Virgin Islands, British','VG','N');
insert into country (country_name, country_code, UN_member) values ('Virgin Islands, U.s.','VI','N');
insert into country (country_name, country_code, UN_member) values ('Wallis And Futuna','WF','N');
insert into country (country_name, country_code, UN_member) values ('Western Sahara','EH','N');
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Yemen','YE','Y',1947);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Zambia','ZM','Y',1964);
insert into country (country_name, country_code, UN_member, UN_member_since) values ('Zimbabwe','ZW','Y',1980);